[project]
name = "sitio-api"
version = "0.1.0"
description = "API del sitio personal."
requires-python = ">=3.10"

[dependency-groups]
prd = [
    "Flask",
    "Flask-Cors",
    "gunicorn",
    "Markdown",
    "python-frontmatter",
    "pydantic",
    "openapi-core",
    'flask-openapi[swagger]==5.0.0rc2',
]

dev = [
    "blue",
    "isort",
    "pytest",
    "pytest-cov",
]

[tool.pytest.ini_options]
pythonpath = ["."]
