name: Promoción de sitio-api desde dev hacia main

on:
  pull_request_review:
    types:
      - submitted

permissions:
  contents: write
  pull-requests: write

jobs:
  promocion:
    if: >
      github.event.review.state == 'approved' &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.ref == 'dev'

    runs-on: ubuntu-latest

    steps:
      - name: Promover dev hacia main
        run: gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
